from __future__ import annotations

import typing

__all__: list[str] = ["MyPyClass", "func1", "func2", "func3"]

class MyPyClass:
    def __init__(self, arg0: typing.SupportsInt) -> None: ...
    @property
    def value(self) -> int: ...

def func1(arg0: MyPyClass) -> MyPyClass: ...
def func2(arg0: MyPyClass) -> MyPyClass: ...
def func3(arg0: MyPyClass) -> MyPyClass: ...
