from __future__ import annotations

import collections.abc
import types
import typing

__all__: list[str] = [
    "TestMapping",
    "get_global_int_map",
    "make_int_int_map",
    "make_str_int_map",
]

class TestMapping:
    def __contains__(self, item: typing.SupportsInt) -> bool: ...
    def __eq__(self, other: typing.Any) -> bool | types.NotImplementedType: ...
    def __getitem__(self, arg0: typing.SupportsInt) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(
        self, arg0: collections.abc.Mapping[typing.SupportsInt, typing.SupportsInt]
    ) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @typing.overload
    def get(self, key: typing.SupportsInt) -> int | None: ...
    @typing.overload
    def get(self, key: typing.SupportsInt, default: int) -> int: ...
    @typing.overload
    def get[T](self, key: typing.SupportsInt, default: T) -> int | T: ...
    def items(self) -> collections.abc.ItemsView[int, int]: ...
    def keys(self) -> collections.abc.KeysView[int]: ...
    def values(self) -> collections.abc.ValuesView[int]: ...

def get_global_int_map() -> collections.abc.Mapping[int, int]: ...
def make_int_int_map() -> collections.abc.Mapping[int, int]: ...
def make_str_int_map() -> collections.abc.Mapping[str, int]: ...
