from __future__ import annotations

__all__: list[str] = ["TestHashIdentity", "TestUnhashable"]

class TestHashIdentity:
    def __hash__(self) -> int: ...
    def __init__(self) -> None: ...

class TestUnhashable:
    def __hash__(self) -> int: ...
    def __init__(self) -> None: ...
