from __future__ import annotations

import collections.abc
import typing

__all__: list[str] = ["TestSequence", "get_sequence"]

class TestSequence:
    def __contains__(self, item: typing.Any) -> bool: ...
    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt) -> int: ...
    @typing.overload
    def __getitem__(self, item: slice) -> list[int]: ...
    def __init__(self) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    def __len__(self) -> int: ...
    def __reversed__(self) -> collections.abc.Iterator[int]: ...
    def count(self, value: typing.SupportsInt) -> int: ...
    def index(
        self,
        value: typing.SupportsInt,
        start: typing.SupportsInt = 0,
        stop: typing.SupportsInt = 9223372036854775807,
    ) -> int: ...

def get_sequence() -> collections.abc.Sequence[int]: ...
