from __future__ import annotations

import collections.abc
import types
import typing

__all__: list[str] = [
    "TestMutableMapping",
    "get_global_int_map",
    "make_int_int_map",
    "make_str_int_map",
]

class TestMutableMapping:
    def __contains__(self, item: str) -> bool: ...
    def __delitem__(self, arg0: str) -> None: ...
    def __eq__(self, other: typing.Any) -> bool | types.NotImplementedType: ...
    def __getitem__(self, arg0: str) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(
        self, arg0: collections.abc.Mapping[str, typing.SupportsInt]
    ) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[str]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: str, arg1: typing.SupportsInt) -> None: ...
    def clear(self) -> None: ...
    @typing.overload
    def get(self, key: str) -> int | None: ...
    @typing.overload
    def get(self, key: str, default: int) -> int: ...
    @typing.overload
    def get[T](self, key: str, default: T) -> int | T: ...
    def items(self) -> collections.abc.ItemsView[str, int]: ...
    def keys(self) -> collections.abc.KeysView[str]: ...
    @typing.overload
    def pop(self, key: str) -> int: ...
    @typing.overload
    def pop(self, key: str, default: int) -> int: ...
    @typing.overload
    def pop[T](self, key: str, default: T) -> int | T: ...
    def popitem(self) -> tuple[str, int]: ...
    @typing.overload
    def setdefault(self, key: str) -> int: ...
    @typing.overload
    def setdefault(self, key: str, default: typing.SupportsInt) -> int: ...
    def update(
        self,
        other: (
            collections.abc.Mapping[str, typing.SupportsInt]
            | collections.abc.Iterable[tuple[str, typing.SupportsInt]]
        ) = (),
        **kwargs: typing.SupportsInt,
    ) -> None: ...
    def values(self) -> collections.abc.ValuesView[int]: ...

def get_global_int_map() -> collections.abc.MutableMapping[int, int]: ...
def make_int_int_map() -> collections.abc.MutableMapping[int, int]: ...
def make_str_int_map() -> collections.abc.MutableMapping[str, int]: ...
