from __future__ import annotations

import numpy
import numpy.typing

__all__: list[str] = [
    "func_double",
    "func_float",
    "func_int16",
    "func_int32",
    "func_int64",
    "func_int8",
    "func_uint16",
    "func_uint32",
    "func_uint64",
    "func_uint8",
]

def func_double(arg0: numpy.typing.NDArray[numpy.float64]) -> None: ...
def func_float(arg0: numpy.typing.NDArray[numpy.float32]) -> None: ...
def func_int16(arg0: numpy.typing.NDArray[numpy.int16]) -> None: ...
def func_int32(arg0: numpy.typing.NDArray[numpy.int32]) -> None: ...
def func_int64(arg0: numpy.typing.NDArray[numpy.int64]) -> None: ...
def func_int8(arg0: numpy.typing.NDArray[numpy.int8]) -> None: ...
def func_uint16(arg0: numpy.typing.NDArray[numpy.uint16]) -> None: ...
def func_uint32(arg0: numpy.typing.NDArray[numpy.uint32]) -> None: ...
def func_uint64(arg0: numpy.typing.NDArray[numpy.uint64]) -> None: ...
def func_uint8(arg0: numpy.typing.NDArray[numpy.uint8]) -> None: ...
